### ISSUE TITLE
Merge fixes from fork

### ISSUE THREAD

**Issue by talldan** [lwansbrough/react-native-multipeer#1]
Hi,

I've noticed this fork of the module:
https://github.com/alex-mcleod/react-native-multipeer

It has a number of small fixes in it for things which currently prevent the module from working out of the box. Just wondering if you have any plans on pulling those changes into your repo, and updating NPM. Having NPM up-to-date would particularly be good!

Thanks.

**Comment by sinanku** [comment]
The example should be cleaned up as well, is anybody having issues with `_.values(MultipeerConnectivy.getAllPeers())` when creating the ListView with lodash?

**Comment by DevanB** [comment]
@sinanulkuatam I'm not seeing any issues with `_.values(MultipeerConnectivity.getAllPeers())`

That being said, I agree with @talldan! I had to make the changes from the fork myself in order to get the module from working out of the box (following the README).

**Comment by nitindhar7** [comment]
I had to use @talldan's fork to make this work as well. would be nice if @lwansbrough could review and merge @talldan's work into the main repo :) Thanks folks! #OpenSourceFTW
