### ISSUE TITLE
React/RCTDefines.h file not found

### ISSUE THREAD

**Issue by qalqi** [lwansbrough/react-native-multipeer#13]
Followed Getting Started steps and we get this error in RN - 0.59

**Comment by qalqi** [comment]
Fixed it by setting 
`$(SRCROOT)/../../ios/Pods/Headers/Public` - `Recursive` in Step 5 of Getting Started

**Comment by soadtechdev** [comment]
<img width="270" alt="Image" src="https://github.com/user-attachments/assets/7c530e96-f9a5-4ab9-b2e6-446f2373f485" />

After adding it I had all these problems
