### ISSUE TITLE
Compile bug and runtime bug.

### ISSUE THREAD

**Issue by zenonmilou** [lwansbrough/react-native-multipeer#2]
So i've had a couple of issues getting this working, im new to React Native so bear with me.

1) On first compile I get the following:
`uncaught error Error: SyntaxError: /Users/Zed/Dev/tagapp/TagApp/node_modules/react-native-multipeer/MultipeerConnection.js: Line 10: 'this' is not allowed before super()`

I added 'super()' in before 'this' and I could get it to compile (was in one more file as well, same error).

2) I was initially confused with an error regarding the use of '_' and then I realised you were probably using 'underscore', might be good to note as you are using it in your example code. Also looks like 'styles.peers' doesnt exist.

3) Once it compiles, on the client I get:
`Listener must be a function`

refering to 

`addListener in event.js @ 102:0`
`componentDidMount in index.ios.js @ 32:0`

The line at 32 is

`'MultipeerConnectivity.on('peerFound', this._onChange());'`

**Comment by lwansbrough** [comment]
Yikes, some messy stuff in there eh? I threw this up really quickly and didn't test everything. I can fix these issues quick. You're incorrect regarding (2) though - underscore is not being used, it's simply a naming convention.

**Comment by lwansbrough** [comment]
@zedman Also your issue on line 32 is you're implicitly calling `this._onChange` when you should just be passing the method reference. Remove the `()` and it should work as you're expecting.

Edit: I see you're using the example code. Whoops!

**Comment by lwansbrough** [comment]
Updated repo. Should resolve the issues you were having.

**Comment by zenonmilou** [comment]
You're a legend, will give it a go soon.

Re. point 2, are you sure thats naming convention?
Line 14: `ds.cloneWithRows(_.values(...)`

**Comment by lwansbrough** [comment]
Oh sorry. This is in the example right? Didn't check there.

**Comment by zenonmilou** [comment]
Yep. All good, thanks for your hard work.
